### ISSUE TITLE
Create a right angled triangle in CPP

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#101]

**Comment by TejaJanakiRam** [comment]
Can you assign me this issue? And by "create a right a angled triangle", do you mean the program should print out several lines consisting of symbols which form a right angled triangle?

**Comment by bishwobista** [comment]
> Can you assign me this issue? And by "create a right a angled triangle", do you mean the program should print out several lines consisting of symbols which form a right angled triangle?

You are right.

**Comment by bishwobista** [comment]
@TejaJanakiRam  You are assigned.
