### ISSUE TITLE
Add your fav DSA problems.

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#15]

**Comment by The-APK** [comment]
I would like to add few problems, kindly assign this to me @bishwobista

**Comment by bishwobista** [comment]
> I would like to add few problems, kindly assign this to me @bishwobista 

Hey, just send a PR 😊

**Comment by Shubhamgulik** [comment]
Hi @bishwobista,
#23 I have raised PR, please review and merge.

**Comment by Somil-Shukla** [comment]
@bishwobista I can add some good dsa problems, Please assign this issue to me

**Comment by naybyal** [comment]
I would like to contribute in Java. Please assign me this task.

**Comment by bishwobista** [comment]
> I would like to contribute in Java. Please assign me this task.

Hey @naybyal , no need, just send a PR

**Comment by bishwobista** [comment]
- **@everyone _star this repo_, for further updates and hacktoberfest 2024 😊💪**

**Comment by Arceen** [comment]
Hey @bishwobista . Please check the PR. Thanks! :)

**Comment by Odin5133** [comment]
Added my favourite problem and my first PR. Thanks @bishwobista

**Comment by AviGawande** [comment]
@bishwobista i would like to contribute to this repo.Hope you will assigned it to me.
