### ISSUE TITLE
Add any programming questions of your interest. [JS] [C] [Python] [Java] [CPP]

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#2]

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by bishwobista** [comment]
> Please Assign this to me

Just submit a pr. 😊

**Comment by sohampathak1234** [comment]
Please assign me this PR 🙋🏻‍♂️
@bishwobista

**Comment by Shubhamgulik** [comment]
Hi @bishwobista ,
I have started with java solutions,
Raised PR for same #25
