### ISSUE TITLE
Add solution to your favourite programming question. [JS] [Python] [CPP] ,etc.

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#4]

**Comment by sid172014** [comment]
Hey @bishwobista i hope you're doing well , can you please assign this issue to me?

**Comment by bishwobista** [comment]
> Hey @bishwobista i hope you're doing well , can you please assign this issue to me?

Hey, just submit a PR 😊

**Comment by manan18** [comment]
Hey @bishwobista , I issued a pull request #5, and added the "Reverse Integer" problem. Please have a look.

**Comment by sid172014** [comment]
Hey @bishwobista added PR #6 which is a solution to the 3sum problem

**Comment by manan18** [comment]
Hey @bishwobista , I issued another PR #7 , and added the "Palindrome Number" Problem. Please have a look.

**Comment by manan18** [comment]
Hey @bishwobista , I have added more problems, but for me to create another PR, you'll have to merge #7 first, so please look into it. Thank You

**Comment by PC-11-00** [comment]
Hey @bishwobista made a PR: !10 have a look at it.

**Comment by manan18** [comment]
PR #11

**Comment by sohampathak1234** [comment]
Please assign me this PR 🙋🏻‍♂️
@bishwobista
