### ISSUE TITLE
[EASY] Add solution to binary search in C++

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#56]
Add the solution to binary search algorithm in the C++ folder

**Comment by Yordaniss** [comment]
Hey @bishwobista . I would like to work on this, can you please assign me to this issue? 🙂

**Comment by bishwobista** [comment]
> Hey @bishwobista . I would like to work on this, can you please assign me to this issue? 🙂

Sure, go ahead 😊

**Comment by harsh-p05** [comment]
Hi, @bishwobista  can i work on this ?

**Comment by bishwobista** [comment]
> Hi, @bishwobista  can i work on this ? 

Unfortunately @Yordaniss asked first. You can raise an issue of any problems/question and raise a PR.
