### ISSUE TITLE
Write a Program to convert Integer to Roman in JavaScript

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/crack-code#94]
Given an integer, convert it to a roman numeral using JavaScript language.

**Comment by RishabhDhawad** [comment]
I want to work on this, can you assign it to me!!

**Comment by bishwobista** [comment]
> I want to work on this, can you assign it to me!!

Sure, @RishabhDhawad

**Comment by AshaHolla** [comment]
This program sounds interesting, can i be assigned as well? Thanks

**Comment by Akshada-26** [comment]
Can you assign it to me, please.

**Comment by bishwobista** [comment]
> This program sounds interesting, can i be assigned as well? Thanks

Unfortunately its been assigned to someone else.
